### ISSUE TITLE
minimal_ns throws exception if hostname not found

### ISSUE THREAD

**Issue by kasgel** [dnshealth/dns-health#18]
./main.py --domain dnshealth.eu --ns dns1.dnshealth.eu dns2.dnshealth.eu dns3.dnshealth.eu
Traceback (most recent call last):
  File "./main.py", line 30, in <module>
    result = check.run(domain,ns)
  File "/home/kasper/nordname/dns-health/src/checks/minimal_ns.py", line 4, in run
    res = unique_ns_list(ns)
  File "/home/kasper/nordname/dns-health/src/checks/minimal_ns.py", line 9, in unique_ns_list
    if unique_ip(l): # If that passes it checks for unique ip
  File "/home/kasper/nordname/dns-health/src/checks/minimal_ns.py", line 27, in unique_ip
    if y == socket.gethostbyname(x):
socket.gaierror: [Errno -2] Name or service not known

This throws an exception if it can not find dns3.dnshealth.eu. It should instead just return false.

**Comment by kasgel** [comment]
Solved
